spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/energy_db?reWriteBatchedInserts=true
    username: postgres
    password: password
  jpa:
    # Validate ensures Hibernate validates the DB schema matches entities but doesn't alter it.
    # We use Flyway for alterations.
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          batch_size: 500 # Group 500 queries into 1 DB network packet
          order_insert: true
          order_updates: true
management:
  endpoints:
    web:
      exposure:
        include: "health,info,metrics"